%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 09-Feb-2026 13:52:22
                     ConfigInfos.Version = '25.2.0.3123386 (R2025b) Update 3';
                   ConfigInfos.SessionID = 'BYD_Dolphin.m';
                   ConfigInfos.LicStatus = [1,1,1,0,0,0,1,0,1];
                ConfigInfos.ProjPathText = 'C:\Users\Sebas\MATLAB\Projects\examples';
                    ConfigInfos.ProjPath = 'C:\Users\Sebas\MATLAB\Projects\examples\VirtualVehicle1\VirtualVehicle';
                 ConfigInfos.SessionName = 'BYD_Dolphin';
                 ConfigInfos.XmlPathText = 'C:\Users\Sebas\MATLAB\Projects\examples\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 1EM';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 3DOF Longitudinal';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 3DOF Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Front Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Simple Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '1EM';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 1EM)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'No Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'No Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'No Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'No IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'No Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('ThermalSystem') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Single-Speed Transmission 1EM';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 1EM with BMS';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntEM1Spd';
           ConfigInfos.DataModified{1,2} = '[0 71.3054 142.6109 213.9163 285.2217 356.5271 388.9292 427.8326 499.138 570.4434 641.7488 713.0543 784.3597 855.6651]';
           ConfigInfos.DataModified{1,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntEM1Spd';
           ConfigInfos.DataModified{1,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{1,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{2,1} = 'PlntEM1Trq';
           ConfigInfos.DataModified{2,2} = '[180 180 180 180 180 180 180 163.6 140.3 122.7 109.1 98.2 89.2 81.8]';
           ConfigInfos.DataModified{2,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntEM1Trq';
           ConfigInfos.DataModified{2,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{2,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{3,1} = 'PlntEM1SpdEff';
           ConfigInfos.DataModified{3,2} = '[0 71.3054 142.6109 213.9163 285.2217 356.5271 388.9292 427.8326 499.138 570.4434 641.7488 713.0543 784.3597 855.6651]';
           ConfigInfos.DataModified{3,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntEM1SpdEff';
           ConfigInfos.DataModified{3,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{3,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{4,1} = 'PlntEM1TrqEff';
           ConfigInfos.DataModified{4,2} = '[0 18 36 54 72 90 108 126 144 162 180]';
           ConfigInfos.DataModified{4,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntEM1TrqEff';
           ConfigInfos.DataModified{4,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{4,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{5,1} = 'PlntEM1EffTbl';
           ConfigInfos.DataModified{5,2} = '[50 78 80 82 82 80 78 78 76 74 70;52 78 80 82 82 80 78 78 76 74 70;52 78 84 86 86 86 86 84 84 82 82;52 80 86 86 88 88 88 86 86 84 84;52 80 86 88 88 88 88 88 86 86 86;52 80 86 88 90 90 90 90 88 88 88;52 82 88 90 91 91 92 92 92 91 91;52 82 88 91 91 92 93 93 93 93 93;52 84 90 92 92 93 93 93 93 93 93;62 86 91 93 93 93 93 93 93 93 93;66 86 91 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;70 86 92 93 93 93 93 93 93 93 93;72 86 91 93 93 93 93 93 93 93 93]';
           ConfigInfos.DataModified{5,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntEM1EffTbl';
           ConfigInfos.DataModified{5,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{5,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{6,1} = 'PlntEM1SpdLoss';
           ConfigInfos.DataModified{6,2} = '[0 139.62634015954637 279.25268031909275 418.87902047863906 468.88888888888891 558.50536063818549 698.13170079773181 837.75804095727813 977.38438111682456 1117.010721276371 1256.6370614359173 1396.2634015954636 1535.88974175501 1675.5160819145563]';
           ConfigInfos.DataModified{6,3} = 'ElectricMachine1.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntEM1SpdLoss';
           ConfigInfos.DataModified{6,5} = 'Electric Vehicle 1EM - Simple Motor';
           ConfigInfos.DataModified{6,6} = 'Electric Machine 1';

           ConfigInfos.DataModified{7,1} = 'PlntVehMass';
           ConfigInfos.DataModified{7,2} = '1405';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehMass';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{8,2} = '1.215';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

           ConfigInfos.DataModified{9,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{9,2} = '1.485';
           ConfigInfos.DataModified{9,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{9,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{9,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{9,6} = 'Body and Frame';

          ConfigInfos.DataModified{10,1} = 'PlntVehAeroFrntArea';
          ConfigInfos.DataModified{10,2} = '2.35';
          ConfigInfos.DataModified{10,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{10,4} = 'PlntVehAeroFrntArea';
          ConfigInfos.DataModified{10,5} = 'Vehicle Body 3DOF Longitudinal';
          ConfigInfos.DataModified{10,6} = 'Body and Frame';

          ConfigInfos.DataModified{11,1} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{11,2} = '0.3';
          ConfigInfos.DataModified{11,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{11,4} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{11,5} = 'Vehicle Body 3DOF Longitudinal';
          ConfigInfos.DataModified{11,6} = 'Body and Frame';

          ConfigInfos.DataModified{12,1} = 'PlntBattSocInit';
          ConfigInfos.DataModified{12,2} = '0.8';
          ConfigInfos.DataModified{12,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{12,4} = 'PlntBattSocInit';
          ConfigInfos.DataModified{12,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{12,6} = 'Energy Storage';

          ConfigInfos.DataModified{13,1} = 'PlntBattNumCellSer';
          ConfigInfos.DataModified{13,2} = '84';
          ConfigInfos.DataModified{13,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{13,4} = 'PlntBattNumCellSer';
          ConfigInfos.DataModified{13,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{13,6} = 'Energy Storage';

          ConfigInfos.DataModified{14,1} = 'PlntBattNumCellPar';
          ConfigInfos.DataModified{14,2} = '30';
          ConfigInfos.DataModified{14,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{14,4} = 'PlntBattNumCellPar';
          ConfigInfos.DataModified{14,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{14,6} = 'Energy Storage';

          ConfigInfos.DataModified{15,1} = 'PlntBattChrgMax';
          ConfigInfos.DataModified{15,2} = '4.5';
          ConfigInfos.DataModified{15,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{15,4} = 'PlntBattChrgMax';
          ConfigInfos.DataModified{15,5} = 'Mapped Battery (Electric Vehicle 1EM)';
          ConfigInfos.DataModified{15,6} = 'Energy Storage';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{1}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{1}.Driver = 'Longitudinal Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnSimTime';
       ConfigInfos.TestPlan{1}.Data{1,2} = '2474';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnLongVelUnit';
       ConfigInfos.TestPlan{1}.Data{2,2} = 'm/s';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{3,2} = '0';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'DriverPreviewDist';
       ConfigInfos.TestPlan{1}.Data{4,2} = '4';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'DriverTimeConst';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0.3';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'DriverAeroRes';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0.5';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'DriverDrivelineRes';
       ConfigInfos.TestPlan{1}.Data{8,2} = '75';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'DriverRollRes';
       ConfigInfos.TestPlan{1}.Data{9,2} = '200';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{10,2} = '15000';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattCurr',...
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattTemp',...
'Battery.BattInfo.BattVolt',...
'Body.BdyFrm.Cg.Vel.xdot',...
'EM.EMTrq',...
};

%% Finish
